openapi: 3.0.3
info:
  title: Duitku Disbursement API
  version: 1.0.0
  description: API Documentation for Duitku Disbursement feature.
servers:
  # - url: https://da7f045c-5294-4f50-865d-4f08695b7b2e.mock.pstmn.io
  #   description: Postman Mock Server (Testing)
  - url: https://sandbox.duitku.com/webapi/api/disbursement
    description: Sandbox Server
  - url: http://localhost:5002/snap
    description: Local Development Server
  - url: http://localhost:3001
    description: testing local proxy
  - url: https://snapdev.duitku.com
    description: testing snap sandbox

# 1. SNAP AUTHORIZATION AND HEADERS
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: "Authentication with bearer token."

security:
  - BearerAuth: []

paths:
  /access-token/b2b:
    post:
      summary: 🔑 Get Access Token (B2B)
      security: [] # Mematikan global Bearer Token khusus untuk endpoint ini
      description: |
        When you're working with web APIs, a Bearer Token is an access token that is often used for authorization purposes. This token acts like a security key that a server uses to verify that the request is coming from an authenticated user or service.

        <div class="alert-box">
          <div class="alert-title">⚠️ Authentication Info</div>
          <div class="alert-content">
            To use a Bearer Token with the SNAP API, you need to obtain the token by providing your credentials to this authentication endpoint. <strong>This endpoint uses the <a href="/security#asymmetric">Asymmetric</a> Signature formula.</strong>
          </div>
        </div>
      tags:
        - Authentication
      
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: "application/json"
          description: "String represents indicate the media type of the resource."
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            default: "2022-09-16T13:00:00+07:00"
          description: "ISO-8601 formatted timestamp."
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
            default: "xJhJTz9ddsPRds..."
          description: |
            Non-Repudiation & Integrity checking X-Signature with [Asymmetric](/security#asymmetric) algorithm. Formula: <br/>
            <code>stringToSign = ClientKey + "|" + Timestamp</code> <br/>
            <code>SHA256withRSA(Private_Key, stringToSign)</code>
        - in: header
          name: X-CLIENT-KEY
          required: true
          schema:
            type: string
            default: "DBXXXX"
          description: "Client Id for disbursement will be provided by Duitku. It'll have different with your project key."

      requestBody:
        required: true
        content:
          application/json:
            examples:
              get token:
                summary: "Request Bearer Token"
                value:
                  grantType: "client_credentials"
            schema:
              type: object
              required:
                - grantType
              properties:
                grantType:
                  type: string
                  description: "The value is 'client_credentials'"
                  example: "client_credentials"

      responses:
        "200":
          description: "Successful processing and obtaining the accessToken"
          content:
            application/json:
              example:
                responseCode: "2007300"
                responseMessage: "Successful"
                accessToken: "ZGMyNDA3NWQtNmM4Ny00NGNiLTQ2NTAtMDhkYWMxNTAzNzY0"
                tokenType: "Bearer"
                expiresIn: "900"
              schema:
                type: object
                properties:
                  responseCode:
                    type: string
                    maxLength: 7
                    description: "Response Code will return status code of request result."
                    example: "2007300"
                  responseMessage:
                    type: string
                    description: "Response Message will return description of request result."
                    example: "Successful"
                  accessToken:
                    type: string
                    description: "String token will be use for every request SNAP API."
                    example: "ZGMyNDA3NWQtNmM4Ny00NGNILTQ2NTAtMDhkYWMxNTAzNzY0"
                  tokenType:
                    type: string
                    description: "Token type that has been created. SNAP use Bearer Token."
                    example: "Bearer"
                  expiresIn:
                    type: string
                    description: "Token duration that can be used. Value count in seconds. 900 seconds = 15 minutes."
                    example: "900"
        "400":
          description: "Bad Request - Invalid Field Format or Missing Mandatory Field"
          content:
            application/json:
              example:
                responseCode: "4007301"
                responseMessage: "Invalid Field Format {grantType}"
        "401":
          description: "Unauthorized - Invalid Client Key or Signature"
          content:
            application/json:
              example:
                responseCode: "4017300"
                responseMessage: "Invalid Client Key or Signature"

  /v1.0/account-inquiry-external:
    post:
      summary: "🔍 Inquiry Request"
      description: |
        <div class="auth-box">
          <div class="auth-title">SNAP Authorization Headers</div>
          <div class="auth-content">
            This API uses SNAP BI standard headers. Ensure you provide the Bearer Token in the authorization configuration, and calculate the <strong>X-SIGNATURE</strong> carefully using the <a href="/security#symmetric">symmetric</a> formula:<br/><br/>
            <code>stringToSign = HttpMethod + ":" + Endpoint + ":" + AccessToken + ":" + LowerCase(HexEncode(SHA-256(Minify(RequestBody)))) + ":" + Timestamp</code><br/><br/>
            <code>signature = Base64(HMAC_SHA512(stringToSign, secretKey))</code>
          </div>
        </div>

        This API is used to perform inquiries for intrabank transfer methods. Duitku supports intrabank transfers for banks connected to the H2H network.
      tags:
        - Inquiry API
      
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: "application/json"
          description: "String represents indicate the media type of the resource."
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            example: "2022-09-16T13:00:00+07:00"
            default: "2022-09-16T13:00:00+07:00"
          description: "ISO-8601 formatted timestamp."
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
            example: "xJhJTz9ddsPRds..."
          description: "Refer to [symmetric](/security#symmetric) signature formula."
        - in: header
          name: X-PARTNER-ID
          required: true
          schema:
            type: string
            example: "DBXXXX"
          description: "Partner ID for disbursement given by Duitku team."
        - in: header
          name: X-EXTERNAL-ID
          required: true
          schema:
            type: string
            example: "REQ-123456789"
          description: "Unique request ID. Need to be unique in every request."
        - in: header
          name: CHANNEL-ID
          required: true
          schema:
            type: string
            example: "95221"
          description: "Value should be 95221."
          
      requestBody:
        required: true
        content:
          application/json:
            examples:
              snap inquiry:
                summary: "Skenario Sukses Internal"
                value:
                  beneficiaryAccountNo: "8760673566"
                  partnerReferenceNo: "767366172360427800000"
                  additionalInfo:
                    deviceId: "12345679237"
                    channel: "mobilephone"
                    amount:
                      value: "10000.00"
                      currency: "IDR"
            schema:
              type: object
              required:
                - beneficiaryAccountNo
                - partnerReferenceNo
                - additionalInfo
              properties:
                beneficiaryAccountNo:
                  type: string
                  maxLength: 34
                  description: "The beneficiary account number for transfer."
                  example: "8760673566"
                partnerReferenceNo:
                  type: string
                  maxLength: 25
                  description: "A unique transaction ID."
                  example: "767366172360427800000"
                additionalInfo:
                  type: object
                  description: "Object value for additional information."
                  required:
                    - amount
                  properties:
                    deviceId:
                      type: string
                      maxLength: 20
                      description: "Device ID of the request origin."
                      example: "12345679237"
                    channel:
                      type: string
                      maxLength: 8
                      description: "Channel of the transaction"
                      example: "014"
                    remark:
                      type: string
                      maxLength: 50 
                      description: "Information that attach to the transaction"
                    amount:
                      type: object
                      required:
                        - value
                        - currency
                      properties:
                        value:
                          type: string
                          description: "Numerical string of amount following with 2 digits decimals."
                          example: "10000.00"
                        currency:
                          type: string
                          maxLength: 3
                          description: "Currency code as in ISO4217 (IDR)."
                          example: "IDR"
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: object
                required:
                  - responseCode
                  - responseMessage
                  - beneficiaryAccountName
                  - beneficiaryAccountNo
                properties:
                  responseCode:
                    type: string
                    maxLength: 7
                    description: "Response code"
                    example: "2001600"
                  responseMessage:
                    type: string
                    maxLength: 150
                    description: "Response description"
                    example: "Successful"
                  referenceNo:
                    type: string
                    maxLength: 64
                    description: "Transaction identifier on service provider system"
                    example: "602169"
                  partnerReferenceNo:
                    type: string
                    maxLength: 64
                    description: "Transaction identifier on service consumer system"
                    example: "767366172360427800000"
                  beneficiaryAccountName:
                    type: string
                    maxLength: 100
                    description: "Beneficiary Account Name"
                    example: "Testing Account"
                  beneficiaryAccountNo:
                    type: string
                    maxLength: 34
                    description: "Beneficiary Account Number"
                    example: "8760673566"
                  beneficiaryBankCode:
                    type: string
                    maxLength: 11
                    description: "Beneficiary Bank Code"
                    example: "014"
                  beneficiaryBankName:
                    type: string
                    maxLength: 50
                    description: "Beneficiary Bank Name"
                    example: "BANK CENTRAL ASIA"
                  additionalInfo:
                    type: object
                    description: "Object value for additional information."
                    required:
                      - amount
                    properties:
                      deviceId:
                        type: string
                        maxLength: 20
                        description: "Device ID of the request origin."
                        example: "12345679237"
                      channel:
                        type: string
                        maxLength: 8
                        description: "Channel of the transaction"
                        example: "mobilephone"
                      remark:
                        type: string
                        maxLength: 50 
                        description: "Information that attach to the transaction"
                      amount:
                        type: object
                        required:
                          - value
                          - currency
                        properties:
                          value:
                            type: string
                            description: "Numerical string of amount following with 2 digits decimals."
                            example: "10000.00"
                          currency:
                            type: string
                            maxLength: 3
                            description: "Currency code as in ISO4217 (IDR)."
                            example: "IDR"

  /v1.0/transfer-interbank:
    post:
      summary: 💸 Transfer Request
      description: |
        <div class="auth-box">
          <div class="auth-title">SNAP Authorization Headers</div>
          <div class="auth-content">
            This API uses SNAP BI standard headers. Ensure you provide the Bearer Token in the authorization configuration, and calculate the <strong>X-SIGNATURE</strong> carefully using the <a href="/security#symmetric">symmetric</a> formula:<br/><br/>
            <code>stringToSign = HttpMethod + ":" + Endpoint + ":" + AccessToken + ":" + LowerCase(HexEncode(SHA-256(Minify(RequestBody)))) + ":" + Timestamp</code><br/><br/>
            <code>signature = Base64(HMAC_SHA512(stringToSign, secretKey))</code>
          </div>
        </div>

        The second step to execute the transfer after successfully validating the destination account via the Inquiry process.
        
        <div class="alert-box">
          <div class="alert-title">⚠️ Important Notes</div>
          <div class="alert-content">
            <ul>
              <li>The <code>X-SIGNATURE</code> header must be generated dynamically on your backend.</li>
              <li><code>partnerReferenceNo</code> must be exactly the same as the one used in the previous Inquiry request to trigger the transfer.</li>
            </ul>
          </div>
        </div>
      tags:
        - Transfer API
      
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: "application/json"
          description: "String represents indicate the media type of the resource."
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            example: "2022-09-16T13:00:00+07:00"
          description: "ISO-8601 formatted timestamp."
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
            example: "xJhJTz9ddsPRds..."
          description: "Refer to [symmetric](/security#symmetric) signature formula."
        - in: header
          name: X-PARTNER-ID
          required: true
          schema:
            type: string
            example: "DBXXXX"
          description: "Partner ID for disbursement given by Duitku team."
        - in: header
          name: X-EXTERNAL-ID
          required: true
          schema:
            type: string
            example: "REQ-123456789"
          description: "Unique request ID. Need to be unique in every request."
        - in: header
          name: CHANNEL-ID
          required: true
          schema:
            type: string
            example: "95221"
          description: "Value should be 95221."

      requestBody:
        required: true
        content:
          application/json:
            examples:
              transfer success:
                summary: "Skenario Sukses"
                value:
                  partnerReferenceNo: "767366172360427800000"
                  sourceAccountNo: "XXXXX"
                  beneficiaryAccountName: "Testing Account"
                  beneficiaryAccountNo: "8760673566"
                  beneficiaryAddress: "Jl. Sudirman No 1, Jakarta"
                  beneficiaryBankCode: "014"
                  beneficiaryBankName: "BANK CENTRAL ASIA"
                  beneficiaryEmail: "test@example.com"
                  transactionDate: "2024-08-08T11:15:38+07:00"
                  amount:
                    value: "10000.00"
                    currency: "IDR"
                  additionalInfo:
                    deviceId: "1234567890"
                    channel: "mobilephone"
                    remark: "Test Transfer"

            schema:
              type: object
              required:
                - partnerReferenceNo
                - sourceAccountNo
                - beneficiaryAccountName
                - beneficiaryAccountNo
                - beneficiaryBankCode
                - transactionDate
                - amount

              properties:
                partnerReferenceNo:
                  type: string
                  maxLength: 25
                  description: "A unique transaction ID. 1 ID for 1 inquiry. Will be use for trigger transfer."
                  example: "767366172360427800000"
                sourceAccountNo:
                  type: string
                  maxLength: 19
                  description: "Your Account Number for disbursement."
                  example: "XXXXX"
                beneficiaryAccountName:
                  type: string
                  maxLength: 100
                  description: "The beneficiary account name."
                  example: "Testing Account"
                beneficiaryAccountNo:
                  type: string
                  maxLength: 34
                  description: "The beneficiary account number for transfer."
                  example: "8760673566"
                beneficiaryAddress:
                  type: string
                  description: "The address of the beneficiary."
                  example: "Jl. Sudirman No 1, Jakarta"
                beneficiaryBankCode:
                  type: string
                  maxLength: 8
                  description: "The beneficiary account bank code for transfer."
                  example: "014"
                beneficiaryBankName:
                  type: string
                  maxLength: 50
                  description: "The beneficiary bank name."
                  example: "BANK CENTRAL ASIA"
                beneficiaryEmail:
                  type: string
                  description: "The email address of the beneficiary."
                  example: "test@example.com"
                transactionDate:
                  type: string
                  description: "Date transaction use format ISO 8601."
                  example: "2024-08-08T11:15:38+07:00"
                amount:
                  type: object
                  description: "Object value that provide amount information."
                  required:
                    - value
                    - currency
                  properties:
                    value:
                      type: string
                      description: "Numerical string of amount following with 2 digits decimals."
                      example: "10000.00"
                    currency:
                      type: string
                      maxLength: 3
                      description: "Currency code as in ISO4217 for Indonesian Rupiah. It should be as IDR."
                      example: "IDR"
                additionalInfo:
                  type: object
                  description: "Object value for additional information that need to be provide."
                  properties:
                    deviceId:
                      type: string
                      description: "Device ID of the request origin."
                      example: "1234567890"
                    channel:
                      type: string
                      description: "Channel of the transaction."
                      example: "mobilephone"
                    remark:
                      type: string
                      maxLength: 100
                      description: "Remark is an information that attach to the transaction."
                      example: "Test Transfer"

      responses:
        "200":
          description: "Successful Transfer"
          content:
            application/json:
              schema:
                type: object
                required:
                  - responseCode
                  - responseMessage
                  - beneficiaryAccountNo
                properties:
                  responseCode:
                    type: string
                    maxLength: 7
                    description: "Response code"
                    example: "2001700"
                  responseMessage:
                    type: string
                    maxLength: 150
                    description: "Response description"
                    example: "Successful"
                  referenceNo:
                    type: string
                    maxLength: 64
                    description: "Transaction identifier on service provider system. Must be filled upon successful transaction"
                    example: "602169"
                  partnerReferenceNo:
                    type: string
                    maxLength: 64
                    description: "Transaction identifier on service consumer system"
                    example: "767366172360427800000"
                  amount:
                    type: object
                    description: "Object value that provide amount information."
                    required:
                      - value
                      - currency
                    properties:
                      value:
                        type: string
                        maxLength: 16
                        description: "Net amount of the transaction. If it's IDR then value includes 2 decimal digits. e.g. IDR 10.000,- will be placed with 10000.00"
                        example: "10000.00"
                      currency:
                        type: string
                        maxLength: 3
                        description: "Currency (ISO4217)"
                        example: "IDR"
                  beneficiaryAccountNo:
                    type: string
                    maxLength: 19
                    description: "Beneficiary Account Number"
                    example: "8760673566"
                  beneficiaryBankCode:
                    type: string
                    maxLength: 11
                    description: "Beneficiary Bank Code"
                    example: "014"
                  additionalInfo:
                    type: object
                    description: "Object value for additional information."
                    required:
                      - amount
                    properties:
                      deviceId:
                        type: string
                        maxLength: 20
                        description: "Device ID of the request origin."
                        example: "12345679237"
                      channel:
                        type: string
                        maxLength: 8
                        description: "Channel of the transaction"
                        example: "mobilephone"
                      remark:
                        type: string
                        maxLength: 50 
                        description: "Information that attach to the transaction"

  /v1.0/balance-inquiry:
    post:
      summary: 💰 Check Balance
      description: |
        <div class="auth-box">
          <div class="auth-title">SNAP Authorization Headers</div>
          <div class="auth-content">
            This API uses SNAP BI standard headers. Ensure you provide the Bearer Token in the authorization configuration, and calculate the <strong>X-SIGNATURE</strong> carefully using the <a href="/security#symmetric">symmetric</a> formula:<br/><br/>
            <code>stringToSign = HttpMethod + ":" + Endpoint + ":" + AccessToken + ":" + LowerCase(HexEncode(SHA-256(Minify(RequestBody)))) + ":" + Timestamp</code><br/><br/>
            <code>signature = Base64(HMAC_SHA512(stringToSign, secretKey))</code>
          </div>
        </div>

        Use this API to check the available balance of your merchant account before performing a disbursement.
      tags:
        - Check Balance
      
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: "application/json"
          description: "String represents indicate the media type of the resource."
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            example: "2022-09-16T13:00:00+07:00"
          description: "ISO-8601 formatted timestamp."
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
            example: "xJhJTz9ddsPRds..."
          description: "Refer to [symmetric](/security#symmetric) signature formula."
        - in: header
          name: X-PARTNER-ID
          required: true
          schema:
            type: string
            example: "DBXXXX"
          description: "Partner ID for disbursement given by Duitku team."
        - in: header
          name: X-EXTERNAL-ID
          required: true
          schema:
            type: string
            example: "REQ-123456789"
          description: "Unique request ID. Need to be unique in every request."
        - in: header
          name: CHANNEL-ID
          required: true
          schema:
            type: string
            example: "95221"
          description: "Value should be 95221."

      requestBody:
        required: true
        content:
          application/json:
            examples:
              check balance:
                summary: "Check Balance"
                value:
                  partnerReferenceNo: "767366172360427800000"
                  accountNo: "XXXXX"
            schema:
              type: object
              required:
                - partnerReferenceNo
                - accountNo
              properties:
                partnerReferenceNo:
                  type: string
                  maxLength: 64
                  description: "A unique transaction ID. Will be used for tracking."
                  example: "767366172360427800000"
                accountNo:
                  type: string
                  maxLength: 16
                  description: "Your Account Number for disbursement."
                  example: "XXXXX"

      responses:
        "200":
          description: "Successful Balance Inquiry"
          content:
            application/json:
              schema:
                type: object
                required:
                  - responseCode
                  - responseMessage
                properties:
                  responseCode:
                    type: string
                    maxLength: 7
                    description: "Response code"
                    example: "2001100"
                  responseMessage:
                    type: string
                    maxLength: 150
                    description: "Response description"
                    example: "Successful"
                  accountInfos:
                    type: array
                    items:
                      type: object
                      properties:
                        amount:
                          type: object
                          required:
                            - value
                            - currency
                          properties:
                            value:
                              type: string
                              maxLength: 16
                              description: "Net amount of the transaction. If it's IDR then value includes 2 decimal digits. e.g. IDR 10.000,- will be placed with 10000.00"
                              example: "10000.00"
                            currency:
                              type: string
                              maxLength: 3
                              description: "Currency (ISO4217)"
                              example: "IDR"
                        availableBalance:
                          type: object
                          required:
                            - value
                            - currency
                          properties:
                            value:
                              type: string
                              maxLength: 16
                              description: "Account balance that can be used for financial transaction"
                              example: "10000.00"
                            currency:
                              type: string
                              maxLength: 3
                              description: "Currency (ISO4217)"
                              example: "IDR"

  /v1.0/transfer/status:
    post:
      summary: 🔎 Check Status
      description: |
        <div class="auth-box">
          <div class="auth-title">SNAP Authorization Headers</div>
          <div class="auth-content">
            This API uses SNAP BI standard headers. Ensure you provide the Bearer Token in the authorization configuration, and calculate the <strong>X-SIGNATURE</strong> carefully using the <a href="/security#symmetric">symmetric</a> formula:<br/><br/>
            <code>stringToSign = HttpMethod + ":" + Endpoint + ":" + AccessToken + ":" + LowerCase(HexEncode(SHA-256(Minify(RequestBody)))) + ":" + Timestamp</code><br/><br/>
            <code>signature = Base64(HMAC_SHA512(stringToSign, secretKey))</code>
          </div>
        </div>

        Use this API to check the latest status of a disbursement transaction. 
        
        <div class="alert-box">
          <div class="alert-title">ℹ️ Note</div>
          <div class="alert-content">
            You can send one parameter between <code>OriginalPartnerReferenceNo</code> or <code>OriginalReferenceNo</code> on the request. Otherwise, you can also send both.
          </div>
        </div>
      tags:
        - Check Status
      
      parameters:
        - in: header
          name: Content-Type
          required: true
          schema:
            type: string
            default: "application/json"
          description: "String represents indicate the media type of the resource."
        - in: header
          name: X-TIMESTAMP
          required: true
          schema:
            type: string
            example: "2022-09-16T13:00:00+07:00"
          description: "ISO-8601 formatted timestamp."
        - in: header
          name: X-SIGNATURE
          required: true
          schema:
            type: string
            example: "xJhJTz9ddsPRds..."
          description: "Refer to [symmetric](/security#symmetric) signature formula."
        - in: header
          name: X-PARTNER-ID
          required: true
          schema:
            type: string
            example: "DBXXXX"
          description: "Partner ID for disbursement given by Duitku team."
        - in: header
          name: X-EXTERNAL-ID
          required: true
          schema:
            type: string
            example: "REQ-123456789"
          description: "Unique request ID. Need to be unique in every request."
        - in: header
          name: CHANNEL-ID
          required: true
          schema:
            type: string
            example: "95221"
          description: "Value should be 95221."

      requestBody:
        required: true
        content:
          application/json:
            examples:
              check status:
                summary: "Check Status Request"
                value:
                  originalPartnerReferenceNo: "810690490886716300000"
                  originalReferenceNo: "602169"
                  originalExternalId: "REQ-123456789"
                  serviceCode: "18"
                  transactionDate: "2024-08-08T11:15:38+07:00"
                  amount:
                    value: "10000.00"
                    currency: "IDR"
                  additionalInfo:
                    deviceId: "1234567890"
                    channel: "mobilephone"
                    remark: "Check Status"

            schema:
              type: object
              required:
                - serviceCode

              properties:
                originalPartnerReferenceNo:
                  type: string
                  maxLength: 64
                  description: "A unique transaction ID that has been used for the transaction. The related ID is required if OriginalReferenceNo is empty."
                  example: "810690490886716300000"
                originalReferenceNo:
                  type: string
                  maxLength: 64
                  description: "Duitku unique generated ID transaction. The related ID is required if OriginalPartnerReferenceNo is empty."
                  example: "602169"
                originalExternalId:
                  type: string
                  maxLength: 32
                  description: "The original external ID used in the transaction request."
                  example: "REQ-123456789"
                serviceCode:
                  type: string
                  maxLength: 2
                  description: |
                    The related API service code that transaction has been transfered.
                    * 17 - Intrabank
                    * 18 - BI-FAST, Interbank
                    * 22 - RTGS
                    * 23 - SKN
                  example: "18"
                transactionDate:
                  type: string
                  maxLength: 25
                  description: "Date transaction use format ISO 8601."
                  example: "2024-08-08T11:15:38+07:00"
                amount:
                  type: object
                  description: "Object value that provide amount information."
                  required:
                    - value
                    - currency
                  properties:
                    value:
                      type: string
                      maxLength: 16
                      description: "Numerical string of amount following with 2 digits decimals."
                      example: "10000.00"
                    currency:
                      type: string
                      maxLength: 3
                      description: "Currency code as in ISO4217 for Indonesian Rupiah. It should be as IDR."
                      example: "IDR"
                additionalInfo:
                  type: object
                  description: "Object value for additional information that need to be provide."
                  properties:
                    deviceId:
                      type: string
                      description: "Device ID of the request origin."
                      example: "1234567890"
                    channel:
                      type: string
                      description: "Channel of the transaction."
                      example: "api"
                    remark:
                      type: string
                      maxLength: 50
                      description: "Remark is an information that attach to the transaction."
                      example: "Check Status"

      responses:
        "200":
          description: "Successful Status Retrieval"
          content:
            application/json:
              schema:
                type: object
                required:
                  - responseCode
                  - responseMessage
                  - serviceCode
                  - beneficiaryAccountNo
                  - referenceNumber
                  - sourceAccountNo
                  - latestTransactionStatus
                properties:
                  responseCode:
                    type: string
                    maxLength: 7
                    description: "Response Code will return status code of request result."
                    example: "2003600"
                  responseMessage:
                    type: string
                    maxLength: 150
                    description: "Response Message will return description of request result."
                    example: "Successful"
                  originalReferenceNo:
                    type: string
                    maxLength: 64
                    description: "Duitku unique generated ID transaction."
                    example: "602412"
                  originalPartnerReferenceNo:
                    type: string
                    maxLength: 64
                    description: "A unique transaction ID. In line with the API service code used by the transaction."
                    example: "810690490886716300000"
                  originalExternalId:
                    type: string
                    maxLength: 32
                    description: "The original external ID used in the transaction request."
                    example: "REQ-123456789"
                  serviceCode:
                    type: string
                    maxLength: 2
                    description: "Transfer Service Code."
                    example: "18"
                  transactionDate:
                    type: string
                    maxLength: 25
                    description: "Date transaction use format ISO 8601."
                    example: "2024-08-08T11:15:38+07:00"
                  beneficiaryAccountNo:
                    type: string
                    maxLength: 34
                    description: "The beneficiary account number from the account that has been inquired."
                    example: "8760673566"
                  beneficiaryBankCode:
                    type: string
                    maxLength: 11
                    description: "The beneficiary bank code."
                    example: "014"
                  previousResponseCode:
                    type: string
                    maxLength: 7
                    description: "The previous response code of the transaction."
                    example: "2001700"
                  referenceNumber:
                    type: string
                    maxLength: 30
                    description: "Bank reference number for the transaction."
                    example: "123456789012"
                  sourceAccountNo:
                    type: string
                    maxLength: 19
                    description: "Your Account Number that has been use for the transaction transfer disbursement."
                    example: "XXXXX"
                  transactionId:
                    type: string
                    maxLength: 8
                    description: "Transaction ID from the core system."
                    example: "TXN-001"
                  latestTransactionStatus:
                    type: string
                    maxLength: 2
                    description: |
                      Transfer Status Code.
                      * 00 - Success
                      * 02 - Paying
                      * 04 - Refunded
                      * 06 - Failed
                    example: "00"
                  transactionStatusDesc:
                    type: string
                    maxLength: 50
                    description: "Transaction Status Description."
                    example: "Success"
                  amount:
                    type: object
                    description: "Object value that provide amount information."
                    required:
                     - value
                     - currency
                    properties:
                      value:
                        type: string
                        description: "Numerical string of amount following with 2 digits decimals."
                        example: "10000.00"
                      currency:
                        type: string
                        maxLength: 3
                        description: "Currency code as in ISO4217 for Indonesian Rupiah. It should be as IDR."
                        example: "IDR"
                  additionalInfo:
                    type: object
                    description: "Object value for additional information that provided by Duitku."
                    properties:
                      deviceId:
                        type: string
                        description: "Device ID of the request origin."
                        example: "1234567890"
                      channel:
                        type: string
                        description: "Channel of the transaction."
                        example: "api"
                      remark:
                        type: string
                        description: "Remark is an information that attach to the transaction."
                        example: "Check Status"